version: '2'


volumes:
  frontera-db: {}


services:

  frontera-db:
    image: postgres:9.5
    volumes:
      - frontera-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "frontera"
      POSTGRES_USER: "ddc"
      POSTGRES_PASSWORD: "ddc"

  zeromq-broker:
    image: dd-crawler
    command: python -m frontera.contrib.messagebus.zeromq.broker --address *
    expose:
      - "5550-5555"

  db-worker-batches:
    image: dd-crawler
    command: /dd_crawler/docker/db_worker.sh --no-incoming
    links:
      - zeromq-broker
    depends_on:
      - frontera-db

  db-worker-incoming-0:
    image: dd-crawler
    command: /dd_crawler/docker/db_worker.sh --no-batches
    links:
      - zeromq-broker
    depends_on:
      - frontera-db

  db-worker-incoming-1:
    image: dd-crawler
    command: /dd_crawler/docker/db_worker.sh --no-batches
    links:
      - zeromq-broker
    depends_on:
      - frontera-db
      - db-worker-incoming-0

  strategy-worker-0:
    image: dd-crawler
    command: /dd_crawler/docker/st_worker.sh --partition-id=0
    links:
      - zeromq-broker
    depends_on:
      - frontera-db

  strategy-worker-1:
    image: dd-crawler
    command: /dd_crawler/docker/st_worker.sh --partition-id=1
    links:
      - zeromq-broker
    depends_on:
      - frontera-db
      - strategy-worker-0

  spider-worker-0:
    image: dd-crawler
    volumes:
      - ./seeds.txt:/dd_crawler/seeds.txt
      - ./out:/dd_crawler/out
    command: /dd_crawler/docker/sp_worker.sh 0 -s SEEDS_SOURCE=/dd_crawler/seeds.txt
    dns:
      - 127.0.0.1
    links:
      - zeromq-broker

  spider-worker-1:
    image: dd-crawler
    volumes:
      - ./out:/dd_crawler/out
    command: /dd_crawler/docker/sp_worker.sh 1
    dns:
      - 127.0.0.1
    links:
      - zeromq-broker

  spider-worker-2:
    image: dd-crawler
    volumes:
      - ./out:/dd_crawler/out
    command: /dd_crawler/docker/sp_worker.sh 2
    dns:
      - 127.0.0.1
    links:
      - zeromq-broker

  spider-worker-3:
    image: dd-crawler
    volumes:
      - ./out:/dd_crawler/out
    command: /dd_crawler/docker/sp_worker.sh 3
    dns:
      - 127.0.0.1
    links:
      - zeromq-broker
