version: '2'


volumes:
  redis-data: {}


services:

  redis:
    image: redis:3.0
    volumes:
      - redis-data:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: [redis-server, /usr/local/etc/redis/redis.conf]

  crawler:
    image: dd-crawler
    volumes:
      - ./seeds.txt:/dd_crawler/seeds.txt
      - ./out:/out
    entrypoint: /dd_crawler/docker/crawl.sh -s SEEDS=/dd_crawler/seeds.txt
    dns:
      - 127.0.0.1
    links:
      - redis
