version: '2'

services:

  zeromq-broker:
    image: dd-crawler
    command: python -m frontera.contrib.messagebus.zeromq.broker --address *
    expose:
      - "5550-5555"

  db-worker:
    image: dd-crawler
    command: [
      python, -m, frontera.worker.db,
       --config=dd_crawler.frontera.worker_settings]
    links:
      - zeromq-broker

# strategy-worker:
#   image: dd-crawler
#   command: [
#     python, -m, frontera.worker.strategy,
#     --config=dd_crawler.frontera.worker_settings,
#     --strategy=frontera.worker.strategies.bfs.CrawlingStrategy,
#     --partition-id=0]
#   links:
#     - zeromq-broker

  spider-worker-0:
    image: dd-crawler
    volumes:
      - ./seeds.txt:/dd_crawler/seeds.txt
    command: scrapy crawl dd_crawler -s SPIDER_PARTITION_ID=0 -s SEEDS_SOURCE=/dd_crawler/seeds.txt
    links:
      - zeromq-broker

  spider-worker-1:
    image: dd-crawler
    command: scrapy crawl dd_crawler -s SPIDER_PARTITION_ID=1
    links:
      - zeromq-broker

  spider-worker-2:
    image: dd-crawler
    command: scrapy crawl dd_crawler -s SPIDER_PARTITION_ID=2
    links:
      - zeromq-broker

  spider-worker-3:
    image: dd-crawler
    command: scrapy crawl dd_crawler -s SPIDER_PARTITION_ID=3
    links:
      - zeromq-broker
